# -*- coding: utf-8 -*-
"""NumPy_Basic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19W2pj2s1sZR-_-OKVMfUgMUdyaX9h3Pt

NumPy Getting Started
"""

import numpy as np
a = np.array([1,2,3,4,5])
print(a)

#Checking NumPy Version
import numpy as np
print(np.__version__)

#Create a NumPy 'ndarray' Object
#The array object in NumPy is called 'ndarray'
#'ndarray' object by using the array() function.

import numpy as np
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

#We can pass a 'list', 'tuple' or any array-like object into the array() method
#And it will be converted into an 'ndarray'
import numpy as np
a = np.array((1,2,3,4,5))
print(a)

"""Dimensions in Arrays

A dimension in arrays is one level of array depth (nested arrays)
"""

#0-D Arrays
import numpy as np
a = np.array(70)
print(a)

#1-D Arrays
import numpy as np
a = np.array([70,73,79])
print(a)

#2-D Arrays
import numpy as np
a = np.array([[10,20,30],[70,73,79]])
print(a)

#3-D arrays
import numpy as np
a = np.array([
              [[10,20,30],[70,73,79]],
              [[1,2,3],[4,5,6]]
            ])
print(a)

#Check Number of Dimensions
import numpy as np
a = np.array(70)
b = np.array([70,73,79])
c = np.array([[10,20,30],[70,73,79]])
d = np.array([
              [[10,20,30],[70,73,79]],
              [[1,2,3],[4,5,6]]
            ])
print("Dimension of array is:",a.ndim,"D")
print("Dimension of array is:",b.ndim,"D")
print("Dimension of array is:",c.ndim,"D")
print("Dimension of array is:",d.ndim,"D")

#Higher Dimensional Arrays
import numpy as np
a = np.array([10,20,30,40],ndmin = 4)
print(a)
print("Dimension of array is:",a.ndim,"D")